# Generated by Django 4.2.23 on 2025-07-24 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMBCChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusting_tube', models.CharField(max_length=100)),
                ('cylinder_body', models.CharField(max_length=100)),
                ('piston_trunnion', models.CharField(max_length=100)),
                ('plunger_spring', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BogieChecksheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axle_guide', models.CharField(max_length=100)),
                ('bogie_frame_condition', models.CharField(max_length=100)),
                ('bolster', models.CharField(max_length=100)),
                ('bolster_suspension_bracket', models.CharField(max_length=100)),
                ('lower_spring_seat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BogieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogie_no', models.CharField(max_length=50)),
                ('maker_year_built', models.CharField(max_length=100)),
                ('incoming_div_and_date', models.CharField(max_length=100)),
                ('deficit_components', models.CharField(max_length=255)),
                ('date_of_ioh', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WheelFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tread_diameter_new', models.CharField(max_length=100)),
                ('last_shop_issue_size', models.CharField(max_length=100)),
                ('condemning_dia', models.CharField(max_length=100)),
                ('wheel_gauge', models.CharField(max_length=100)),
                ('variation_same_axle', models.CharField(max_length=100)),
                ('variation_same_bogie', models.CharField(max_length=100)),
                ('variation_same_coach', models.CharField(max_length=100)),
                ('wheel_profile', models.CharField(max_length=100)),
                ('intermediate_wwp', models.CharField(max_length=100)),
                ('bearing_seat_diameter', models.CharField(max_length=100)),
                ('roller_bearing_outer_dia', models.CharField(max_length=100)),
                ('roller_bearing_bore_dia', models.CharField(max_length=100)),
                ('roller_bearing_width', models.CharField(max_length=100)),
                ('axle_box_housing_bore_dia', models.CharField(max_length=100)),
                ('wheel_disc_width', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=50, unique=True)),
                ('submitted_by', models.CharField(max_length=100)),
                ('submitted_date', models.DateField()),
                ('status', models.CharField(default='Saved', max_length=50)),
                ('fields', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.wheelfields')),
            ],
        ),
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=50, unique=True)),
                ('inspection_by', models.CharField(max_length=100)),
                ('inspection_date', models.DateField()),
                ('status', models.CharField(default='Saved', max_length=50)),
                ('bmbc_checksheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.bmbcchecksheet')),
                ('bogie_checksheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.bogiechecksheetdata')),
                ('bogie_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.bogiedetails')),
            ],
        ),
    ]
