# Generated by Django 4.2.23 on 2025-07-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bogiechecksheet',
            options={'ordering': ['-inspection_date']},
        ),
        migrations.AlterModelOptions(
            name='wheelspecification',
            options={'ordering': ['-submitted_date']},
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='status',
            field=models.CharField(choices=[('Saved', 'Saved'), ('Submitted', 'Submitted')], default='Saved', max_length=50),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='status',
            field=models.CharField(choices=[('Saved', 'Saved'), ('Submitted', 'Submitted')], default='Saved', max_length=50),
        ),
    ]
